version: '3.5'

services:

  local-leitor-planilha-db:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: "cidades-db"
      POSTGRES_USER: "leitor_planilha_user"
      POSTGRES_PASSWORD: "leitor_planilha_password"
    ports:
      - 5442:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data2
    container_name: local-cidades-db
    networks:
      - leitor-planilha-shared-net

  integ-test-db:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: "cidades-db-integtest"
      POSTGRES_USER: "leitor_planilha_user"
      POSTGRES_PASSWORD: "leitor_planilha_password"
    ports:
      - 5443:5432
    container_name: local-integ-test-cidades-db
    networks:
      - leitor-planilha-shared-net

  redis:
    image: redis:5.0.6-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    container_name: local-cidades-db-redis
    networks:
      - leitor-planilha-shared-net

volumes:
  postgres-data:
    external: false
  redis-data:
    external: false
  redis.conf:
    external: false

networks:
  leitor-planilha-shared-net:
    name: leitor-planilha-shared-net
