spring:
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: dev
  application:
    name: leitor-planilha-service
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      data-source-properties:
        stringtype: unspecified
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 30s

cache:
  ttl_seconds:
    getCities: 1800 # 30 minutos
    getRegions: 1800 # 30 minutos
    getStates: 1800 # 30 minutos