server.port: 8082
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5442/cidades-db
      username: leitor_planilha_user
      password: leitor_planilha_password
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        cache: TRACE