server.port: 8082
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5442/cidades-db
      username: leitor_planilha_user
      password: leitor_planilha_password
      connection-test-query: SELECT 1
    redis:
      hostname: localhost
      port: 6379
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org:
      springframework:
        cache: TRACE