server.port: 7777
server.shutdown: immediate

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5443/cidades-db-integtest
      username: leitor_planilha_user
      password: leitor_planilha_password
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379